services:
  acestream:
    image: wafy80/acestream
    container_name: acestream
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "6878:6878"
      - "8621:8621"
    command: >
      --client-console
      --bind-all
      --live-buffer 30
      --upload-limit 1

  acestream-api:
    image: acestream-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: acestream-api
    ports:
      - "6877:6877"
    depends_on:
      - acestream
    restart: unless-stopped
    env_file:
      - .env
