services:
  acelink:
    image: wafy80/acestream
    container_name: acelink
    ports:
      - "6878:6878"
      - "8621:8621"
    restart: unless-stopped
    networks:
      - acestream

  acelink-api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
    container_name: acelink-api
    ports:
      - "4000:4000"
    depends_on:
      - acelink
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    networks:
      - acestream
    # volumes:
    #   - ./apps/api/src:/app/src

  acelink-web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
    container_name: acelink-web
    ports:
      - "4001:4001"
    depends_on:
      - acelink
      - acelink-api
    restart: unless-stopped
    env_file:
      - "./apps/web/.env"
    networks:
      - acestream
    # volumes:
    #   - ./apps/web/src:/app/src

networks:
  acestream:
