services:
  acestream:
    image: wafy80/acestream
    container_name: acestream
    ports:
      - 6878:6878
      - 8621:8621/udp
    platform: linux/amd64
    restart: unless-stopped

  acestream-api:
    image: acestream-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: acestream-api
    ports:
      - "6877:6877"
    depends_on:
      - acestream
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=6877
      - ACE_URL=http://acestream:6878

  acestream-web:
    image: acestream-web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: acestream-web
    ports:
      - "6876:6876"
    depends_on:
      - acestream
      - acestream-api
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - HOSTNAME=${HOSTNAME}
      - BACKEND_URL=${BACKEND_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - PANGOLIN_TOKEN=${PANGOLIN_TOKEN}

networks:
  default:
