services:
  acestream:
    image: blaiseio/acelink
    container_name: acestream
    platform: linux/amd64
    restart: unless-stopped

  acestream-api:
    image: acestream-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: acestream-api
    depends_on:
      - acestream
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=6877
      - ACE_URL=http://acestream:6878

  acestream-web:
    image: acestream-web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: acestream-web
    depends_on:
      - acestream
      - acestream-api
    restart: unless-stopped
    env_file:
      - ./apps/web/.env

networks:
  default:
