services:
  acelink:
    image: blaiseio/acelink
    container_name: acelink
    ports:
      - "6878:6878"
    restart: unless-stopped
    networks:
      - network

  acelink-api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: acelink-api
    ports:
      - "4000:4000"
    depends_on:
      - acelink
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    networks:
      - network

  acelink-web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: acelink-web
    ports:
      - "4001:4001"
    depends_on:
      - acelink
      - acelink-api
    restart: unless-stopped
    env_file:
      - "./apps/web/.env"
    networks:
      - network

networks:
  network:
