services:
  acelink:
    image: blaiseio/acelink
    container_name: acelink
    ports:
      - "6878:6878"
    restart: unless-stopped

  acelink-middleware:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: ace-middleware
    ports:
      - "4000:4000"
    depends_on:
      - acelink
    restart: unless-stopped
    env_file:
      - .env

  acelink-webui:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: ace-webui
    ports:
      - "4000:4000"
    depends_on:
      - acelink-middleware
    restart: unless-stopped
    env_file:
      - .env

networks:
  acestream:
