services:
  acestream:
    image: blaiseio/acelink
    container_name: acestream
    ports:
      - "6878:6878"
    platform: linux/amd64
    restart: unless-stopped

  acestream-api:
    image: acestream-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: acestream-api
    ports:
      - "6877:6877"
    depends_on:
      - acestream
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=6877
      - ACE_URL=http://acestream:6878

networks:
  default:
